### ISSUE TITLE
Allow sequences with Ns

### ISSUE THREAD

**Issue by maehler** [maehler/seqpoet#11]

**Comment by davizze** [comment]
Hi, 
here the primer sequences with degenerate bases I used to perform insilico PCR:
CCTACGGGRBGCASCAG
GCTGACGRCRRCCATGC
You can use few sequences of bacterial 16S rRNA. This primer set amplifies around 96% of all the bacteria. 

This is the command line I used after I used primers with non-degenerated bases:
seqpoet --pcr --min-product 430 --max-product 550 -o rpd_seqpoet.fasta /Users/davipo/Dropbox/Documents/Project/USA2work/seqpoet/rdp_download_252995seqs.fa /Users/davipo/Dropbox/Documents/Project/USA2work/seqpoet/primers.txt 

and this is the error:

Traceback (most recent call last):
  File "/usr/local/bin/seqpoet", line 4, in <module>
    __import__('pkg_resources').run_script('seqpoet==0.3.3', 'seqpoet')
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/seqpoet-0.3.3-py2.7.egg/EGG-INFO/scripts/seqpoet", line 441, in <module>
    main()
  File "/Library/Python/2.7/site-packages/seqpoet-0.3.3-py2.7.egg/EGG-INFO/scripts/seqpoet", line 410, in main
    minus_revcomp=args.minus_revcomp)
  File "/Library/Python/2.7/site-packages/seqpoet-0.3.3-py2.7.egg/EGG-INFO/scripts/seqpoet", line 153, in match_primer
    for i, record in enumerate(f):
  File "/Library/Python/2.7/site-packages/seqpoet-0.3.3-py2.7.egg/seqpoet/fasta.py", line 225, in generate_records
    yield self.get_record(i)
  File "/Library/Python/2.7/site-packages/seqpoet-0.3.3-py2.7.egg/seqpoet/fasta.py", line 217, in get_record
    return FastaRecord(Sequence(seq), indexdict['name'])
  File "/Library/Python/2.7/site-packages/seqpoet-0.3.3-py2.7.egg/seqpoet/sequence.py", line 37, in __init__
    'only supports DNA sequences')
ValueError: ('illegal characters in sequence, currently ', 'only supports DNA sequences')

**Comment by maehler** [comment]
Apparently we already allow Ns in sequences, so it seems to be purely a matter of allowing all the other IUPAC nucleotide codes. I'll close this issue and use #3 for this work.
